nav:
  Accueil: /
  À Propos: /apropos/
  Blog: /blog/
  Services: /services/
  Projets: /projets/

projects_url: https://github.com/cheredeprince

customize:
    gravatar:
        email: 
    logo:
        enabled: true
        width: 50
        height: 50
        url: /img/logo.png
        gravatar: false
    favicon: 
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /img/favicon.ico
        gravatar: false
      android:
        url: /img/favicon-192x192.png
        gravator: false
      apple:
        url: /img/apple-touch-icon.png
        gravator: false

    show_all_posts: false
    post_count: 5
    highlight: rainbow

# RSS
rss: atom.xml

# Plugins
plugins:
    disqus_shortname: # Disqus Comments Shortname
    google_analytics: false

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
